user backend_user
topic readwrite visionbot/#

user robot01_user
topic read visionbot/+/cmd/#
topic read visionbot/+/ai/#
topic write visionbot/+/state
topic write visionbot/+/telemetry
topic write visionbot/+/event
topic write visionbot/+/cmd_ack

pattern readwrite visionbot/%u/#
